# Сборка фронтенда
FROM node:20-alpine

ARG VITE_API_URL
ARG VITE_ALLOWED_HOSTS

ENV VITE_API_URL=$VITE_API_URL
ENV VITE_ALLOWED_HOSTS=$VITE_ALLOWED_HOSTS

WORKDIR /app

# Копируем package файлы сначала (для кэширования слоев)
COPY package.json package-lock.json ./
RUN npm install

# Копируем env файлы
COPY .env.development .env

# Копируем остальной код
COPY . .

CMD ["npm", "run", "dev"]
