# Stage 1: сборка фронтенда
FROM node:20-alpine AS builder

WORKDIR /app

# Копируем package.json и package-lock.json
COPY package.json package-lock.json ./

# Устанавливаем зависимости
RUN npm ci --only=production

# Копируем исходный код
COPY . .

# Собираем приложение
RUN npm run build

# Stage 2: serve build
FROM node:20-alpine

WORKDIR /app

# Копируем собранное приложение из builder stage
COPY --from=builder /app/dist ./dist

# Устанавливаем serve глобально
RUN npm install -g serve

# Экспонируем порт
# EXPOSE 80

# Запускаем сервер для статики
CMD ["serve", "-s", "dist", "-l", "80"]