# Stage 1: сборка фронтенда
FROM node:20-alpine AS builder

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm install

COPY . .

# Копируем env файл
# COPY .env.staging .env

RUN npm run build

# Stage 2: serve build
FROM node:20-alpine

WORKDIR /app
COPY --from=builder /app/dist ./dist

RUN npm install -g serve

CMD ["serve", "-s", "dist", "-l", "80"]
