services:
  backend:
    labels:
      - "traefik.enable=false"
    ports:
      - "8000:${BACKEND_PORT}"

  nginx:
    labels:
      - "traefik.enable=false"
    ports:
      - "8080:${NGINX_PORT}"

  telegram_bot:
    labels:
      - "traefik.enable=false"
    ports:
      - "8443:${TELEGRAM_BOT_PORT}"

  frontend:
    labels:
      - "traefik.enable=false"
    ports:
      - "5173:${FRONTEND_PORT}"
    volumes:
      - ./frontend/src:/app/src:rw
      - ./frontend/public:/app/public:rw
      - ./frontend/index.html:/app/index.html:rw
      - ./frontend/vite.config.js:/app/vite.config.js:rw
      - ./frontend/package.json:/app/package.json:rw
      - /app/node_modules
