# Generated by Django 5.2.8 on 2025-11-24 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('admin', '0001_initial'),  # ✅ ДОБАВЬ эту зависимость
    ]

    operations = [
        migrations.RunSQL(
            """
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_c564eba6_fk_auth_user_id;

            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_fk_users_user_id 
            FOREIGN KEY (user_id) REFERENCES users_user(id);
            """,
            """
            ALTER TABLE django_admin_log 
            DROP CONSTRAINT IF EXISTS django_admin_log_user_id_fk_users_user_id;

            ALTER TABLE django_admin_log 
            ADD CONSTRAINT django_admin_log_user_id_c564eba6_fk_auth_user_id 
            FOREIGN KEY (user_id) REFERENCES auth_user(id);
            """
        ),
    ]