# Generated by Django 5.2.9 on 2025-12-21 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_fix_admin_log_constraint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
    ]
