# Generated by Django 5.2.9 on 2026-01-26 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_user_photo_user_avatar_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iiko_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Iiko ID'),
        ),
    ]
