# Generated by Django 5.2.10 on 2026-01-26 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_iiko_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='iiko_qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='iiko_qr_codes/', verbose_name='Статические QR'),
        ),
    ]
