# Generated by Django 5.2.10 on 2026-02-01 00:40

import uuid
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models

def populate_referral_codes(apps, schema_editor):
    User = apps.get_model("users", "User")

    for user in User.objects.all():
        user.referral_code = uuid.uuid4()
        user.save(update_fields=["referral_code"])

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_user_iiko_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='referral_code',
            field=models.UUIDField(null=True, editable=False),
        ),
        migrations.RunPython(
            populate_referral_codes,
            migrations.RunPython.noop
        ),
        migrations.AlterField(
            model_name='user',
            name='referral_code',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name="Реферальный код"),
        ),
        migrations.AddField(
            model_name='user',
            name='referrer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='referrals', to=settings.AUTH_USER_MODEL, verbose_name='Реферер'),
        ),
    ]
