# Generated by Django 5.2.12 on 2026-04-05 09:38

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_remove_user_rating_user_points_alter_user_knockouts'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRewardLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation', models.CharField(choices=[('CREDITING', 'Зачисление'), ('DEDUCTING', 'Списание')], max_length=50, verbose_name='Тип операции')),
                ('reward', models.CharField(choices=[('KNOCKOUTS', 'Knockouts'), ('POINTS', 'Points')], max_length=50, verbose_name='Тип награды')),
                ('count', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Кол-во')),
                ('comment', models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rewards', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал наград пользователя',
                'verbose_name_plural': 'Журналы наград пользователей',
            },
        ),
    ]
