server {
    listen 80;

    location /storage/avatars/ {
        alias /storage/avatars/;
        add_header Cache-Control "public";
    }

    location /static/ {
        alias /staticfiles/;
        add_header Cache-Control "public, immutable";
    }

    location /storage/ {
        return 404;
    }
}
