server {
    listen 80;

    location /storage/avatars/ {
        alias /storage/avatars/;
    }

    location /static/ {
        alias /staticfiles/;
    }

    location /storage/ {
        return 404;
    }
}
