# Generated by Django 5.2.8 on 2025-11-24 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tournament',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, verbose_name='Название')),
                ('location', models.CharField(max_length=128, verbose_name='Локация')),
                ('started_at', models.DateTimeField(help_text="Если указать прошедшую дату, статус автоматически станет 'Активный'", verbose_name='Дата старта')),
                ('max_participants', models.PositiveIntegerField(help_text='Максимальное количество участников', verbose_name='Количество мест')),
                ('general_rules', models.TextField(verbose_name='Общие правила')),
                ('features', models.TextField(help_text='Каждая особенность с новой строки', verbose_name='Особенности')),
                ('status', models.CharField(choices=[('IN_QUEUE', 'В очереди'), ('ACTIVE', 'Активный'), ('INACTIVE', 'Неактивный')], default='IN_QUEUE', max_length=20, verbose_name='Статус')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Турнир',
                'verbose_name_plural': 'Турниры',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('title', 'started_at'), name='unique_tournament_title_per_date')],
            },
        ),
    ]
