# Generated by Django 5.2.8 on 2025-11-25 16:30

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='features',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='general_rules',
        ),
        migrations.AddField(
            model_name='tournament',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(default='', verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TournamentRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('REGISTERED', 'Зарегистрирован'), ('WAITLIST', 'В листе ожидания'), ('CANCELLED', 'Отменена')], default='REGISTERED', max_length=20, verbose_name='Статус регистрации')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('table_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Номер стола')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='tournaments.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Регистрация на турнир',
                'verbose_name_plural': 'Регистрации на турниры',
                'ordering': ['created_at'],
                'unique_together': {('tournament', 'user')},
            },
        ),
    ]
