# Generated by Django 5.2.9 on 2025-12-24 21:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_remove_tournament_features_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='description',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='max_participants',
        ),
        migrations.AddField(
            model_name='tournament',
            name='general_rules',
            field=models.TextField(default='Правила не указаны.', verbose_name='Общие правила'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='TournamentFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=256, verbose_name='Текст особенности')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features_list', to='tournaments.tournament')),
            ],
            options={
                'verbose_name': 'Особенность турнира',
                'verbose_name_plural': 'Особенности турнира',
                'ordering': ['sort_order'],
            },
        ),
    ]
