# Generated by Django 5.2.9 on 2026-01-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0003_remove_tournament_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(default=100, help_text='Максимальное количество участников', verbose_name='Количество мест'),
        ),
    ]
