# Generated by Django 5.2.10 on 2026-01-28 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0004_tournament_max_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='max_waitlist',
            field=models.PositiveIntegerField(default=60, help_text='Максимальное количество ожидающих', verbose_name='Количество ожидающих'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_participants',
            field=models.PositiveIntegerField(default=60, help_text='Максимальное количество участников', verbose_name='Количество участников'),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text="Если указать прошедшую дату, статус автоматически станет 'Активный'", verbose_name='Дата старта'),
        ),
        migrations.AlterField(
            model_name='tournamentregistration',
            name='status',
            field=models.CharField(choices=[('REGISTERED', 'Зарегистрирован'), ('WAITLIST', 'В листе ожидания')], default='REGISTERED', max_length=20, verbose_name='Статус регистрации'),
        ),
    ]
