# Generated by Django 5.2.10 on 2026-01-29 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0005_tournament_max_waitlist_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tournament',
            name='started_at',
            field=models.DateTimeField(help_text="Если указать прошедшую дату, статус автоматически станет 'Активный'", verbose_name='Дата старта'),
        ),
    ]
