# Generated by Django 5.2.10 on 2026-02-01 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0006_alter_tournament_started_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to='tournaments/icons/', verbose_name='Иконка'),
        ),
    ]
