# Generated by Django 5.2.12 on 2026-03-25 13:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0007_tournament_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournament',
            name='olap_report_completed',
            field=models.BooleanField(default=False, verbose_name='OLAP отчет проведен'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='attended',
            field=models.BooleanField(default=False, verbose_name='Пользователь присутствовал'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='knockouts',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Нокауты'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='points',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Очки рейтинга'),
        ),
    ]
