# Generated by Django 5.2.12 on 2026-04-05 10:40

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0008_tournament_olap_report_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TournamentRewardDistributionTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64, unique=True, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата регистрации')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
            ],
            options={
                'verbose_name': 'Шаблон распределения наград турнира',
                'verbose_name_plural': 'Шаблоны распределения наград турниров',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='bank_points',
            field=models.DecimalField(decimal_places=2, default=Decimal('10000.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Общий банк очков'),
        ),
        migrations.AddField(
            model_name='tournamentregistration',
            name='rankings_calculated',
            field=models.BooleanField(default=False, verbose_name='Рейтинги учтены'),
        ),
        migrations.CreateModel(
            name='TournamentConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_point', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Очки за Entry (все)')),
                ('add_on_point', models.DecimalField(decimal_places=2, default=Decimal('40.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Очки за Add-on')),
                ('bounty_green_point', models.DecimalField(decimal_places=2, default=Decimal('25.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Очки за BountyGreen')),
                ('bounty_blue_point', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Очки за BountyBlue')),
                ('bounty_red_point', models.DecimalField(decimal_places=2, default=Decimal('100.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Очки за BountyRed')),
                ('bounty_gold_point', models.DecimalField(decimal_places=2, default=Decimal('50.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Очки за BountyGold')),
                ('tournament', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='config', to='tournaments.tournament', verbose_name='Турнир')),
            ],
            options={
                'verbose_name': 'Конфигурация турнира',
                'verbose_name_plural': 'Конфигурации турниров',
            },
        ),
        migrations.CreateModel(
            name='TournamentEventLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(choices=[('ENTRY', 'Entry'), ('RE_ENTRY', 'Re-entry'), ('FREE_ENTRY', 'Free Entry'), ('FREE_RE_ENTRY', 'Free Re-entry'), ('ADD_ON', 'Add-on'), ('BOUNTY_GREEN', 'BountyGreen'), ('BOUNTY_BLUE', 'BountyBlue'), ('BOUNTY_RED', 'BountyRed'), ('BOUNTY_GOLD', 'BountyGold'), ('ELIMINATION', 'Elimination')], max_length=50, verbose_name='Событие')),
                ('count', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Кол-во')),
                ('multiplier', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Множитель очков')),
                ('recorded_at', models.DateTimeField(verbose_name='Дата записи')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('tournament', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='tournaments.tournament', verbose_name='Турнир')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tournament_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Журнал событий турнира',
                'verbose_name_plural': 'Журналы событий турниров',
            },
        ),
        migrations.AddField(
            model_name='tournament',
            name='reward_distribution_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournaments', to='tournaments.tournamentrewarddistributiontemplate', verbose_name='Шаблон распределения наград'),
        ),
        migrations.CreateModel(
            name='TournamentRewardDistribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Позиция')),
                ('percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0')), django.core.validators.MaxValueValidator(Decimal('100'))], verbose_name='Процент очков от общего банка')),
                ('bonus_points', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Бонусные очки')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reward_distributions', to='tournaments.tournamentrewarddistributiontemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Распределение наград турнира',
                'verbose_name_plural': 'Распределение наград турниров',
                'ordering': ['position'],
                'unique_together': {('template', 'position')},
            },
        ),
    ]
