# Generated by Django 5.2.12 on 2026-04-05 10:41

from django.db import migrations

def create_missing_configs(apps, schema_editor):
    """
    Создаёт TournamentConfig для всех турниров, у которых его нет
    """
    # Получаем исторические версии моделей (важно для миграций!)
    Tournament = apps.get_model('tournaments', 'Tournament')
    TournamentConfig = apps.get_model('tournaments', 'TournamentConfig')

    # Находим турниры без конфига
    tournaments_without_config = Tournament.objects.filter(config__isnull=True)

    created_count = 0
    for tournament in tournaments_without_config:
        # Создаём конфиг со значениями по умолчанию
        TournamentConfig.objects.create(tournament=tournament)
        created_count += 1
        print(f"  Created config for tournament #{tournament.id}: {tournament.title}")

    if created_count:
        print(f"✅ Created {created_count} missing tournament configs")
    else:
        print("✅ All tournaments already have configs")

def reverse_func(apps, schema_editor):
    """
    Откат миграции (опционально) - удаляем созданные конфиги
    """
    TournamentConfig = apps.get_model('tournaments', 'TournamentConfig')
    # Удаляем конфиги, которые были созданы в прямой миграции
    # ВАЖНО: удалятся все конфиги, созданные этой миграцией
    # Проще оставить reverse_func пустым, если не нужен откат
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0009_tournamentrewarddistributiontemplate_and_more'),
    ]

    operations = [
        migrations.RunPython(create_missing_configs, reverse_func),
    ]
