# Generated by Django 5.2.12 on 2026-04-05 10:43

from decimal import Decimal
from django.db import migrations, transaction

def create_classic_reward_distribution_template(apps, schema_editor):
    # Получаем исторические версии моделей (важно для миграций!)
    TournamentRewardDistributionTemplate = apps.get_model('tournaments', 'TournamentRewardDistributionTemplate')
    TournamentRewardDistribution = apps.get_model('tournaments', 'TournamentRewardDistribution')

    if TournamentRewardDistributionTemplate.objects.filter(title="classic").exists():
        return

    rewards = {
      1: {"percent": Decimal("25")},
      2: {"percent": Decimal("16")},
      3: {"percent": Decimal("12")},
      4: {"percent": Decimal("9")},
      5: {"percent": Decimal("8")},
      6: {"percent": Decimal("7")},
      7: {"percent": Decimal("6")},
      8: {"percent": Decimal("5.25")},
      9: {"percent": Decimal("4.25")},
      10: {"percent": Decimal("2")},
      11: {"percent": Decimal("1.75")},
      12: {"percent": Decimal("1.5")},
      13: {"percent": Decimal("1.25")},
      14: {"percent": Decimal("1")},
      15: {"bonus_points": Decimal("50")}
    }

    with transaction.atomic():
        template = TournamentRewardDistributionTemplate.objects.create(title="classic")

        to_create = []
        for position, data in rewards.items():
            percent = data.get("percent", Decimal("0"))
            bonus_points = data.get("bonus_points", Decimal("0"))

            to_create.append(
                TournamentRewardDistribution(
                    template=template,
                    position=position,
                    percent=percent,
                    bonus_points=bonus_points
                )
            )

        TournamentRewardDistribution.objects.bulk_create(to_create)

        print(f"✅ Created classic tournament_reward_distribution_template")

def reverse_func(apps, schema_editor):
    """
    Откат миграции (опционально) - удаляем созданные конфиги
    """
    TournamentRewardDistributionTemplate = apps.get_model('tournaments', 'TournamentRewardDistributionTemplate')
    TournamentRewardDistributionTemplate.objects.filter(title="classic").delete()

class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0010_create_missing_tournament_configs'),
    ]

    operations = [
        migrations.RunPython(create_classic_reward_distribution_template, reverse_func),
    ]
