# Generated by Django 5.2.13 on 2026-04-20 09:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0011_create_classic_tournament_reward_distribution_template'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenteventlog',
            name='comment',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='tournamenteventlog',
            name='event',
            field=models.CharField(choices=[('ENTRY', 'Entry'), ('RE_ENTRY', 'Re-entry'), ('FREE_ENTRY', 'Free Entry'), ('FREE_RE_ENTRY', 'Free Re-entry'), ('FREE_ENTRY_DEP', 'Free Entry Dep'), ('ADD_ON', 'Add-on'), ('BOUNTY_GREEN', 'BountyGreen'), ('BOUNTY_BLUE', 'BountyBlue'), ('BOUNTY_RED', 'BountyRed'), ('BOUNTY_GOLD', 'BountyGold'), ('ELIMINATION', 'Elimination')], max_length=50, verbose_name='Событие'),
        ),
        migrations.AlterField(
            model_name='tournamenteventlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tournament_events', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
    ]
