# Generated by Django 5.2.13 on 2026-04-22 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0012_tournamenteventlog_comment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tournamenteventlog',
            name='is_valid',
            field=models.BooleanField(default=True, verbose_name='Валидный для расчета'),
        ),
    ]
