# Generated by Django 5.2.9 on 2025-12-23 20:59

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/')),
                ('alt', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Изображение',
                'verbose_name_plural': 'Изображения',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='AboutClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TEXT', 'Текст'), ('GALLERY', 'Галерея')], default='TEXT', max_length=20, verbose_name='Тип блока')),
                ('sort_order', models.PositiveIntegerField(default=0, help_text='Чем больше число, тем ниже блок в списке', verbose_name='Порядок сортировки')),
                ('text', django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Текст')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('images', models.ManyToManyField(blank=True, related_name='blocks', to='about_club.aboutimage', verbose_name='Изображения')),
            ],
            options={
                'verbose_name': "Блок 'О клубе'",
                'verbose_name_plural': "Блоки 'О клубе'",
                'ordering': ['sort_order'],
            },
        ),
    ]
