# Generated by Django 5.2.9 on 2025-12-23 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_club', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutclub',
            name='type',
        ),
        migrations.AlterField(
            model_name='aboutclub',
            name='images',
            field=models.ManyToManyField(blank=True, help_text='Изображения для блока', related_name='blocks', to='about_club.aboutimage', verbose_name='Изображения'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='alt',
            field=models.CharField(blank=True, max_length=255, verbose_name='Alt текст'),
        ),
        migrations.AlterField(
            model_name='aboutimage',
            name='image',
            field=models.ImageField(upload_to='about/', verbose_name='Изображение'),
        ),
    ]
