# Generated by Django 5.2.9 on 2025-12-23 21:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about_club', '0002_remove_aboutclub_type_alter_aboutclub_images_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aboutclub',
            name='images',
        ),
        migrations.AlterModelOptions(
            name='aboutclub',
            options={'ordering': ['sort_order', '-created_at'], 'verbose_name': "Блок 'О клубе'", 'verbose_name_plural': "Блоки 'О клубе'"},
        ),
        migrations.AlterField(
            model_name='aboutclub',
            name='sort_order',
            field=models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки'),
        ),
        migrations.CreateModel(
            name='AboutClubImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='about/blocks/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, help_text='Описание изображения для SEO и доступности', max_length=255, verbose_name='Alt текст')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата загрузки')),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_images', to='about_club.aboutclub', verbose_name='Блок')),
            ],
            options={
                'verbose_name': 'Изображение блока',
                'verbose_name_plural': 'Изображения блока',
                'ordering': ['sort_order', '-uploaded_at'],
            },
        ),
        migrations.DeleteModel(
            name='AboutImage',
        ),
        migrations.AddIndex(
            model_name='aboutclubimage',
            index=models.Index(fields=['block', 'sort_order'], name='about_club__block_i_07ac6c_idx'),
        ),
    ]
