# Generated by Django 5.2.10 on 2026-01-29 23:22

from django.db import migrations

def create_default_about_club(apps, schema_editor):
    AboutClub = apps.get_model("about_club", "AboutClub")

    if AboutClub.objects.exists():
        return

    default_text = (
        "<p><strong>Hi, Jack! Poker Club</strong> — это спортивно-развлекательный покерный клуб для тех, кто любит игру, атмосферу и соревновательный дух."
        "<br>Мы играем <strong>в спортивный покер — не на деньги</strong>, а на рейтинг и нематериальные достижения."
        "<br>В клубе <strong>нет денежных ставок и денежных выигрышей</strong>. Все фишки, карты и столы — это игровой инвентарь для турнирного процесса."
        "<br>Турниры проходят по прозрачному регламенту, фиксируются в рейтинговой системе клуба и сопровождаются администратором и неиграющими дилерами."
        "<br>Взносы участников носят <strong>организационный характер</strong> и направлены на проведение турниров и развитие клуба."
        "<br>Hi, Jack! — это:</p>"
        "<ul>"
            "<li data-list-item-id=\"e6b8ef3a5c75fd60b8496f853422a2ca5\">честная игра и понятные правила</li>"
            "<li data-list-item-id=\"e60831ca2550c9fbf3a9073a097ccbdeb\">рейтинг, баунти и фирменные механики</li>"
            "<li data-list-item-id=\"eae97d189c1dd7d0926e93d4b45395268\">уважение к соперникам и атмосфере</li>"
            "<li data-list-item-id=\"ef0b9418dfdfffa8c1da42bcb51af13b4\">покер как интеллектуальный спорт и событие</li>"
            "<li data-list-item-id=\"e0ee88270557a1c8164ffae3249a6b11c\">алкогольное и безалкогольное сопровождение</li>"
            "<li data-list-item-id=\"e7943cd985ea0b6a8a17220123037c828\">лучшие кальянные мастера</li>"
        "</ul>"
        "<p>Присоединяясь к клубу, вы становитесь частью сообщества, где нам важны <strong>ВЫ.</strong><br><strong>Hi, Jack! — это про людей.</strong></p>"
    )

    AboutClub.objects.create(text=default_text, sort_order=1)

class Migration(migrations.Migration):
    dependencies = [
        ('about_club', '0003_remove_aboutclub_images_alter_aboutclub_options_and_more'),
    ]

    operations = [
        migrations.RunPython(create_default_about_club)
    ]
