# Generated by Django 5.2.9 on 2025-12-30 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SocialNetwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social_type', models.CharField(choices=[('map', 'Карта (Map)'), ('tg', 'Telegram'), ('vk', 'ВКонтакте'), ('ig', 'Instagram'), ('vk_broadcast', 'VK Трансляции'), ('vk_broadcast_archive', 'Архив VK Трансляций')], max_length=30, unique=True, verbose_name='Тип')),
                ('url', models.URLField(blank=True, help_text='Например: https://t.me/your_channel', max_length=500, verbose_name='Ссылка')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Ссылка на соцсеть',
                'verbose_name_plural': 'Ссылки на соцсети',
                'ordering': ['social_type'],
            },
        ),
    ]
