# Generated by Django 5.2.10 on 2026-01-29 19:17

from django.db import migrations

def create_default_socials(apps, schema_editor):
    SocialNetwork = apps.get_model("social_network", "SocialNetwork")
    
    defaults = {
        "map": "https://yandex.ru/maps/org/khay_dzhek_klab_/83743013847?si=hkgyga7pje6fw6n1znjpxqhjk0",
        "ig": "https://www.instagram.com/hi_jack_club",
        "vk": "https://vk.com/hijackclub",
        "tg": "https://t.me/HJC_club",
        "vk_broadcast": "https://vk.com/hijackclub",
        "vk_broadcast_archive": "https://vk.com/hijackclub",
    }
    
    for social_type, url in defaults.items():
        SocialNetwork.objects.get_or_create(
            social_type=social_type, 
            defaults={"url": url}
        )

class Migration(migrations.Migration):
    dependencies = [
        ('social_network', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_socials),
    ]
